# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6bb80289add1be01df1c8b255501beeedfe80937b641d4f75336b95fe9b7ef6b10f606c0e875c057719b81e046378f7412559a94bb51a6dd1eb6a555dd127e

test:
  secret_key_base: 0b5195f5bcd54297c5829dfe6a2319875e7cafcec9d0882af88d4626e697063431be26fa29d008c6e85371adf5040942c8ad39c89dfae21bd3addf75b8862eef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
